enable_ssl: false

epel_repo_name: epel-mcc
remi_repo_name: remi
remiphp74_repo_name: remi-php74

environment:
  http_proxy: http://proxy-web.culture.fr:8000
  https_proxy: http://proxy-web.culture.fr:8000

proxy_env:
  http_proxy: http://proxy-web.culture.fr:8000
  https_proxy: http://proxy-web.culture.fr:8000

virtualhosts:
  gobelins:
    servernames:
      - cmn-recette.culture.fr
      - admin.cmn-recette.culture.fr
    run_queue_worker: false
    has_scheduled_jobs: false
  datasource:
    servernames:
      - datasource.cmn-recette.culture.fr
    run_queue_worker: false
    has_scheduled_jobs: false
