enable_ssl: false

deployer_user: ned

ansistrano_git_branch: master

proxy_env:
  http_proxy: _none_
  https_proxy: _none_

virtualhosts:
  gobelins:
    servernames:
      - beta.collections-mobilier-national.com
      - admin.beta.collections-mobilier-national.com
      - www.beta.collections-mobilier-national.com
    redirects:
      - www.beta.collections-mobilier-national.com
    run_queue_worker: false
    has_scheduled_jobs: false
  datasource:
    servernames:
      - datasource.collections-mobilier-national.com
    run_queue_worker: false
    has_scheduled_jobs: false
