enable_ssl: false

virtualhosts:
  gobelins:
    servernames:
      - beta.collections-mobilier-national.com
      - admin.beta.collections-mobilier-national.com
    run_queue_worker: false
    has_scheduled_jobs: false
  datasource:
    servernames:
      - datasource.collections-mobilier-national.com
    run_queue_worker: false
    has_scheduled_jobs: false
