# file: roles/elasticsearchtier/tasks/elasticsearch-yum-repo.yml
- name: Import PGP key for elasticsearch RPM repository
  tags: elasticsearch
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Enable elasticsearch RPM repository permanently
  tags: elasticsearch
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    enabled: 1
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/GPG-KEY-elasticsearch
