# file: roles/elasticsearchtier/tasks/elasticsearch-plugins.yml
- elasticsearch_plugin:
    name: analysis-icu
    state: present
    proxy_host: "{{ proxy_host }}"
    proxy_port: "{{ proxy_port }}"
