- name: Chown shared storage to nginx:nginx
  become: true
  become_user: root
  file: path={{ ansistrano_deploy_to }}/shared/storage state=directory owner=nginx group=nginx recurse=yes mode=0755

- name: Chown shared public dir to nginx:nginx
  become: true
  become_user: root
  file: path={{ ansistrano_deploy_to }}/shared/public state=directory owner=nginx group=nginx recurse=yes mode=0755
