# file: roles/webtier/tasks/dotenv.yml
- name: Check if .env template exists
  tags: dotenv
  local_action: stat path=dotenv_templates/{{ inventory_hostname }}.{{ item.key }}.j2
  vars:
     ansible_become: no
  with_dict: "{{ virtualhosts }}"
  register: dotenv_file

- name: Create node spesific .env file  
  tags: dotenv
  template: src={{ item.stat.path }} dest=/var/www/{{ item.item.key }}/.env
  with_items: "{{ dotenv_file.results }}"  
  when: item.stat.exists == True
