# file: roles/webtier/tasks/php.yml
- name: Install PHP and extensions
  yum:
    name:
      - php74
      - php74-php
      - php74-php-common
      - php74-php-bcmath
      - php74-php-pdo
      - php74-php-mbstring
      - php74-php-xml
      - php74-php-pgsql
      - php74-php-mysqlnd
      - php74-php-json
      - php74-php-opcache
    state: installed
    enablerepo: "{{ epel_repo_name }},{{ remi_repo_name }},{{ remiphp74_repo_name }}"
  tags: php
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install PHP and extensions
  apt:
    name:
      - php7.4
      - php7.4-pdo
      - php7.4-mbstring
      - php7.4-tokenizer
      - php7.4-xml
      - php7.4-mysqlnd
      - php7.4-opcache
    state: installed
    update_cache: yes
  tags: php
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install extra PHP packages
  yum:
    name: "{{ php_extra_packages }}"
    state: installed
    enablerepo: "{{ epel_repo_name }},{{ remi_repo_name }},{{ remiphp74_repo_name }}"
  tags: php-extra
  when: php_extra_packages is defined and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')
  notify:
    - Restart php-fpm

- name: Install extra PHP packages
  apt:
    name: "{{ php_extra_packages }}"
    state: installed
    update_cache: yes
  tags: php-extra
  when: php_extra_packages is defined and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
  notify:
    - Restart php-fpm (Debian)

- name: Set PHP memory limit in php.ini
  tags: php
  ini_file:
    dest: /etc/php.ini
    section: "PHP"
    option: memory_limit
    value: "{{ php_memory_limit }}"
  when: php_memory_limit is defined and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')
  notify:
    - Restart php-fpm

- name: Set PHP memory limit in php.ini
  tags: php
  ini_file:
    dest: "{{ item }}"
    section: "PHP"
    option: memory_limit
    value: "{{ php_memory_limit }}"
  with_items:
    - /etc/php/7.4/apache2/php.ini
    - /etc/php/7.4/fpm/php.ini
    - /etc/php/7.4/cli/php.ini
  when: php_memory_limit is defined and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
  notify:
    - Restart php-fpm (Debian)
