# Clean up releases
- name: ANSISTRANO | Clean up releases
  become: true
  become_user: root
  shell: ls -1dt {{ ansistrano_releases_path }}/* | tail -n +{{ ansistrano_keep_releases | int + 1 }} | xargs sudo rm -rf
  when: ansistrano_keep_releases > 0
