- name: Add unprivileged deployer user
  tags: deployer_user
  user:
    name: "{{ deployer_user }}"
    state: present
    createhome: yes
    shell: /bin/bash
    append: yes

- name: Add proxy config for git for deployer user
  tags: deployer_user
  git_config:
    name: http.proxy
    scope: system
    value: "{{ proxy_env.http_proxy }}"
  when: proxy_env.http_proxy
